# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_categorycode', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('vchr_categoryname', models.CharField(blank=True, max_length=30, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'category',
            },
        ),
    ]
