# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
                ('vchr_address', models.CharField(blank=True, max_length=250, null=True)),
                ('int_gstin', models.BigIntegerField(blank=True, null=True)),
                ('vchr_mail', models.CharField(blank=True, max_length=150, null=True)),
                ('vchr_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('vchr_logo', models.CharField(blank=True, max_length=350, null=True)),
                ('vchr_print_logo', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'company',
            },
        ),
    ]
