# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_from', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('int_credit_days', models.IntegerField(blank=True, null=True)),
                ('bint_credit_limit', models.BigIntegerField(blank=True, null=True)),
                ('dat_po_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('bint_tin_no', models.BigIntegerField(blank=True, null=True)),
                ('bint_cst_no', models.BigIntegerField(blank=True, null=True)),
                ('vchr_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_gstin_status', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_account_group', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_pan_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dealer',
            },
        ),
        migrations.CreateModel(
            name='DealerAddress',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_address', models.CharField(blank=True, max_length=180, null=True)),
                ('vchr_email', models.CharField(blank=True, max_length=30, null=True)),
                ('bint_phone_no', models.BigIntegerField(blank=True, null=True)),
                ('int_pincode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dealer_address',
            },
        ),
        migrations.CreateModel(
            name='DealerContactPerson',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_desigination', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_department', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_office', models.CharField(blank=True, max_length=50, null=True)),
                ('bint_mobile_no1', models.BigIntegerField(blank=True, null=True)),
                ('bint_mobile_no2', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dealer_contact_person',
            },
        ),
    ]
