# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vchr_name', models.CharField(max_length=50)),
                ('vchr_address', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_email', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'branch',
            },
        ),
    ]
